#!/usr/bin/python
"""This script will calculate the storage capacity required for a Zabbix installation in a large environment"""
class Capacity(object):
    def __init__(self,
                 hosts,
                 items_per_host,
                 monitor_frequency,
                 history_item_size,
                 trend_item_size,
                 event_size,
                 history_period,
                 trend_period,
                 events_freq):
        try:
            self.hosts = int(hosts)
            self.items_per_host = int(items_per_host)
            self.monitor_frequency = int(monitor_frequency)
            self.history_item_size = int(history_item_size)
            self.trend_item_size = int(trend_item_size)
            self.event_size = int(event_size)
            self.history_period = int(history_period)
            self.trend_period = int(trend_period)
            self.events = int(events_freq)
        except ValueError, AttributeError:
            print "Wrong input values entered or missing information", ValueError, AttributeError

    def nvps(self):
        vps = (self.hosts * self.items_per_host) / self.monitor_frequency
        return vps

    # Depending on the database engine used, type of received values
    # (floats, integers, strings, log files, etc), the disk space for keeping a single value
    # may vary from 40 bytes to hundreds of bytes. Normally it is around 50 bytes per value.
    # depending on database type, requires about 128 bytes per each total.
    # Suppose we would like to keep trend data for 6 months.
    # event requires approximately 130 bytes of disk space. It is hard to estimate the number of events
    # generated by Monza daily. In the worst case scenario, we may assume that Monza generates one
    # event per second.

    def dbsize(self):
        historysize = self.nvps() * self.history_item_size * self.history_period * 60 * 60 * 24
        trendsize = self.hosts * self.items_per_host * self.trend_item_size * self.trend_period * 24
        eventsize = self.events * self.event_size * 60 * 60 * 24 * 365
        dbsize = historysize + trendsize + eventsize
        return dbsize


if __name__ == '__main__':
    site1 = Capacity(
        raw_input('No of hosts to monitor:'),
        raw_input('No of monitors per host:'),
        raw_input('Monitor frequency(seconds):'),
        raw_input('Average size of a historical data receieved (Default = 50B):') or 50,
        raw_input('Average size of a trend data (Default = 128B):') or 128,
        raw_input('Average size of a event data (Default = 130B):') or 130,
        raw_input('Historical data retention period(days):'),
        raw_input('Trend data retention period(days):'),
        raw_input('No of events per second(Default = 1):') or 1)

    print ""
    print "New Values per Second = ", site1.nvps()
    print "Database size for history, trend and events data = ", site1.dbsize() / (1024 * 1024 * 1024), "GB"
